services:
  nginx:
    image: nginx:1.27.2 # Newest version (As of 22.12.2024)
    restart: always
    env_file: ".env"
    ports:
      - "80:80" # HTTP Port
      - "${NIFI_HTTP_PORT}:${NIFI_HTTP_PORT}" # NiFi Node Connection over HTTP Port 
      - "${NIFI_FLOW_HTTP_PORT}:${NIFI_FLOW_HTTP_PORT}" # NiFi Flow Server Node Connection over HTTP Port
    networks:
      - nifi_cluster
    configs: # Override config
      - source: nginx_conf
        target: /etc/nginx/conf.d/default.conf
    depends_on:
      - nifi
  # Single instance zookeeper
  zookeeper:
    image: zookeeper:3.9.3 # Newest version (As of 22.12.2024)
    restart: always
    networks:
      - nifi_cluster
    env_file: ".env"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_MY_ID=1
      - ZOO_SERVERS=server.1=zookeeper:2888:3888;2181
  # Cluster
  nifi:
    image: apache/nifi:1.28.1 # Newest version before NiFi 2.0 (As of 22.12.2024)
    restart: always
    deploy:
      mode: replicated
      replicas: ${NIFI_NODE_COUNT} # Number of nodes in cluster
      endpoint_mode: vip
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    networks:
      - nifi_cluster
    volumes:
      - ./data:/data # Persistent directory volume
    env_file: ".env"
    environment:
      - NIFI_WEB_HTTP_PORT=${NIFI_HTTP_PORT}
      - NIFI_CLUSTER_IS_NODE=true
      - NIFI_CLUSTER_NODE_PROTOCOL_PORT=8082
      - NIFI_ZK_CONNECT_STRING=zookeeper:2181
      - NIFI_ZK_CLIENT_SECURE=false
      - NIFI_ELECTION_MAX_WAIT=20 sec
      - NIFI_SENSITIVE_PROPS_KEY=${NIFI_SENSITIVE_KEY}
    depends_on:
      zookeeper:
        condition: service_started # Only start all nodes if zookeeper already started

networks:
  nifi_cluster:
    driver: bridge

configs:
  nginx_conf:
    file: ./conf/nginx/default.conf