services:
  nginx:
    image: nginx
    restart: always
    depends_on:
      - nifi
    ports:
      - "80:80"
      - "8080:8080"
      - "8081:8081"
      - "8443:8443"
    networks:
      - nifi_cluster
    configs:
      - source: nginx_conf
        target: /etc/nginx/conf.d/default.conf
  # Single instance zookeeper
  zookeeper:
    image: zookeeper:latest
    restart: always
    hostname: zookeeper
    ports:
      - 2181:2181
    networks:
      - nifi_cluster
    env_file: ".env"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_MY_ID=1
      - ZOO_SERVERS=server.1=zookeeper:2888:3888;2181
  # Cluster
  nifi:
    image: apache/nifi:1.19.1
    restart: always
    expose:
      - ${NIFI_HTTP_PORT}
      - 8081
    deploy: # Automatic load balancing
      mode: replicated
      replicas: ${NIFI_NODE_COUNT}
      endpoint_mode: vip
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    networks:
      - nifi_cluster
    volumes:
      - ./data:/data
    env_file: ".env"
    environment:
      - NIFI_WEB_HTTP_PORT=${NIFI_HTTP_PORT}
      - NIFI_CLUSTER_IS_NODE=true
      - NIFI_CLUSTER_NODE_PROTOCOL_PORT=8082
      - NIFI_ZK_CONNECT_STRING=zookeeper:2181
      - NIFI_ZK_CLIENT_SECURE=false
      - NIFI_ELECTION_MAX_WAIT=20 sec
      - NIFI_SENSITIVE_PROPS_KEY=ctsBtRBKHRAx69EqUghvvgEvjnaLjFEB
    depends_on:
      zookeeper:
        condition: service_started

networks:
  nifi_cluster:
    driver: bridge

configs:
  nginx_conf:
    file: ./conf/nginx/default.conf